name: Atualizar README com Issues de Vagas

on:
  issues:
    types: [opened, edited, deleted, closed, reopened, labeled, unlabeled]
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
      
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Instalar dependências
        run: npm install @octokit/rest
      
      - name: Atualizar README com issues
        run: node .github/scripts/update-readme.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Commit e push das alterações
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "docs: atualiza lista de vagas no README"
          git push
